# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170112_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='gcm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
